const Passageiro = [
  {
    id: '1',
    passageiro: 'Mario',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro2.jpeg'),
    sobre: 'Sou o Mario, gosto de viagens emocionantes e mantenho a calma em situações difíceis.',
    telefone: '123-456-7890',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '2',
    passageiro: 'Cleusa',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro6.jpeg'),
    sobre: 'Oi, eu sou a Cleusa. Gosto de viajar e aproveitar o trajeto com tranquilidade.',
    telefone: '987-654-3210',
    avaliacao: 'Neutra',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '3',
    passageiro: 'Silvia',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro8.jpeg'),
    sobre: 'Eu sou a Silvia, confiante e tranquila, aproveito cada viagem ao máximo.',
    telefone: '555-555-5555',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '4',
    passageiro: 'George',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro4.jpeg'),
    sobre: 'Oi, sou o George. Encaro as viagens de forma positiva e gosto de novos desafios.',
    telefone: '123-123-1234',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '5',
    passageiro: 'Amarilio',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro5.jpeg'),
    sobre: 'E aí, sou o Amarilio. Gosto de aventuras e encaro o desconhecido com coragem.',
    telefone: '999-888-7777',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '6',
    passageiro: 'Salete',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro6.jpeg'),
    sobre: 'Olá, sou a Salete. Desfruto das viagens com determinação e tranquilidade.',
    telefone: '333-333-3333',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '7',
    passageiro: 'Leonor',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro7.jpeg'),
    sobre: 'Sou a Leonor. Encaro cada viagem com confiança e positividade.',
    telefone: '777-777-7777',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
  {
    id: '8',
    passageiro: 'Paulo',
    data: '12/04/2024',
    foto: require('../assets/img/passageiro3.jpeg'),
    sobre: 'Oi, sou o Paulo. Gosto de explorar novos lugares e aproveitar cada momento.',
    telefone: '666-666-6666',
    avaliacao: 'Muito Positiva',
    documentacao: 'Confirmado',
    email: 'Confirmado',
    celular: 'Confirmado',
  },
];

export default Passageiro;