const Motorista = [
  {
    id: '1',
    motorista: 'Lucas',
    data: '12/04/2024',
    foto: require('../assets/img/perigoso_fortao.jpg'),
    sobre: 'Sou motorista que curte o PERIGO, e nunca fico NERVOSO',
    telefone: '123-456-7890',
    valor: Math.floor(Math.random() * 100) + 20,
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '2',
    motorista: 'Jeovhaldo',
    data: '12/04/2024',
    foto: require('../assets/img/motorista_carlo.png'),
    sobre: 'Meu nome é Jeovhaldo! Pode contar comigo para uma viagem tranquila e sem complicações.',
    telefone: '987-654-3210',
    valor: Math.floor(Math.random() * 100) + 20,
    avaliacao: 'Muito Positiva', 
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '3',
    motorista: 'Freddy',
    data: '12/04/2024',
    foto: require('../assets/img/motorista_lula.png'),
    sobre: 'Oie, eu sou o Freddy! Sempre pronto para ajudar você durante a viagem.',
    telefone: '555-555-5555',
    valor: Math.floor(Math.random() * 100) + 20, 
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '4',
    motorista: 'Juliano',
    data: '12/04/2024',
    foto: require('../assets/img/PERIGO_TOTAL.png'),
    sobre: 'Opa!! Eu sou o Juliano. Estou aqui para oferecer o melhor serviço possível a você.',
    telefone: '123-123-1234',
    valor: Math.floor(Math.random() * 100) + 20, 
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '5',
    motorista: 'Adailton',
    data: '12/04/2024',
   foto: require('../assets/img/PERIGO_DESARMADO.png'),
    sobre: 'E aí, galera? Eu sou o Adailton! Pode relaxar e aproveitar a viagem comigo.',
    telefone: '999-888-7777',
    valor: Math.floor(Math.random() * 100) + 20, 
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '6',
    motorista: 'Espartano',
    data: '12/04/2024',
    foto: require('../assets/img/motorista_jojo.jpeg'),
    sobre: 'Oi, pessoal! Aqui é o Espartano. Estou aqui para garantir que você aguenta a pressão.',
    telefone: '333-333-3333',
    valor: Math.floor(Math.random() * 100) + 20,
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '7',
    motorista: 'Leandrinha',
    data: '12/04/2024',
    foto: require('../assets/img/motorista1.jpg'),
    sobre: 'Olá ! Eu sou a Leandrinha! Estou aqui para tornar nossa viagem animada e cheia de boas vibrações.',
    telefone: '777-777-7777',
    valor: Math.floor(Math.random() * 100) + 20, 
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
  {
    id: '8',
    motorista: 'Irineu',
    data: '12/04/2024',
    foto: require('../assets/img/motorista1.jpg'),
    sobre: 'Olá, pessoal! Eu sou o Irineu. Comigo, você pode confiar em uma viagem tranquila e segura.',
    telefone: '666-666-6666',
    valor: Math.floor(Math.random() * 100) + 20, 
    avaliacao: 'Muito Positiva',
    veiculo: 'Mercerdes',
    placa: 'CTR2312',
    cor: 'Preto',
    assentos: Math.floor(Math.random() * 4) + 1,
  },
];

export default Motorista;
